apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
    test: v2
spec:
  replicas: {{ rc.frontend.number }}
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
        test: v2
    spec:
      containers:
      - name: {{ rc.frontend.name }}
        image: {{ rc.frontend.image }}:{{ rc.frontend.version }}
        ports:
        - containerPort: {{ rc.frontend.port }}
