{{ $frontend_replicas  := attr "rc/frontend/number" }}
{{ $container_name     := attr "rc/frontend/name" }}
{{ $container_image    := attr "rc/frontend/image" }}
{{ $container_version  := attr "rc/frontend/version" }}
{{ $container_port     := attr "rc/frontend/port" }}

apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
    test: v2
spec:
  replicas: {{ $frontend_replicas }}
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
        test: v2
    spec:
      containers:
      - name: {{ $container_name }}
        image: {{ $container_image }}:{{ $container_version }}
        ports:
        - containerPort: {{ $container_port }}
