apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
    test: v2
spec:
  replicas: {{ rc.redis-master.number }}
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
        test: v2
    spec:
      containers:
      - name: {{ rc.redis-master.name }}
        image: {{ rc.redis-master.image }}:{{ rc.redis-master.version }}
        ports:
        - containerPort: {{ rc.redis-master.port }}
