apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
  labels:
    name: redis-slave
    test: v2
spec:
  replicas: {{ rc.redis-slave.number }}
  selector:
    name: redis-slave
  template:
    metadata:
      labels:
        name: redis-slave
        test: v2
    spec:
      containers:
      - name: {{ rc.redis-slave.name }}
        image: {{ rc.redis-slave.image }}:{{ rc.redis-slave.version }}
        ports:
        - containerPort: {{ rc.redis-slave.port }}
