{{ $port := attr "svc/redis-slave/port" }}

apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-slave
    test: v2
spec:
  ports:
    # the port that this service should serve on
  - port: {{ $port }} # 6379
  selector:
    name: redis-slave
